### ISSUE TITLE
Jest doesn't find any test files on windows

### ISSUE THREAD

**Issue by DorianGrey** [DorianGrey/ng-webpack-template#21]
Just recognized the `appveyor` build failing after the most recent update of `jest` to `23.2.0`.

There are already a couple of issues open regarding this:
https://github.com/facebook/jest/issues/6546
https://github.com/facebook/jest/issues/6509

Have to figure out if it's possible to work around this using a different `testMatch` config.

**Comment by wideawakewesley** [comment]
@DorianGrey Didn't know where best to ask this, but I'm having trouble with jest finding any test files on Win10 using 23.6.0. Even when I pass in a direct path to a test file it fails to find it. Didn't want to raise a new bug in case I was being really dense. Would appreciate any help you can give.

Example with direct path trying with win & linux paths:

e.g.
$ node_modules/.bin/jest C:\\Users\\WESLEYWilliams\\git\\<myrepo>\\test\\fvt\\__tests__\\my.test.js
No tests found
No files found in C:\Users\WESLEYWilliams\git\<myrepo>.
Make sure Jest's configuration does not exclude this directory.
To set up Jest, make sure a package.json file exists.
Jest Documentation: facebook.github.io/jest/docs/configuration.html
Pattern: C:\Users\WESLEYWilliams\git\<myrepo>\test\fvt\__tests__\my.test.js - 0 matches
 
$ node_modules/.bin/jest /c/Users/WESLEYWilliams/git/<myrepo>/test/fvt/__tests__/my.test.js
No tests found
No files found in C:\Users\WESLEYWilliams\git\<myrepo>.
Make sure Jest's configuration does not exclude this directory.
To set up Jest, make sure a package.json file exists.
Jest Documentation: facebook.github.io/jest/docs/configuration.html
Pattern: C:\\Users\\WESLEYWilliams\\git\\<myrepo>\\test\\fvt\\__tests__\\my.test.js - 0 matches

**Comment by DorianGrey** [comment]
I've checked this on Win 10, and both ways of providing a file path resp. pattern work fine, i.e. I cannot reproduce this issue, neither on `jest` 23.5 nor on 23.6.
Additional details on your project would be useful, i.e. a repo to reproduce this issue with.

**Comment by wideawakewesley** [comment]
@DorianGrey Unfortunately I can't share the repo, but what kind of project details might I be able to provide that could help?

**Comment by DorianGrey** [comment]
It seems to have something to do with the `roots` property. When removing it, I also get the latter result on Win10. The same result occurs when changing to array to only reference the test folder, like:
```
"roots": [
   "<rootDir>/test/"
 ]
```
In general - is there any particular reason to define `rootDir` and `roots` explicitly? In most cases, this is not required.
Side note: The patterns you have defined for `testMatch` appear a bit weird, suppose you want to cover `js` and `jsx` files, and not `jx`, right? At least the patterns mention that the `s` is optional, so `.jx` would be a covered file extension. `jsx?` should be more useful in this case.
