### ISSUE TITLE
typo: stale comment on store-freeze

### ISSUE THREAD

**Issue by GiuseppePiscopo** [DorianGrey/ng-webpack-template#6]
At [this line](https://github.com/DorianGrey/ng-webpack-template/blob/c138754f137a1090ba7fac6fdfd482c965b2cda1/src/app/app.store.ts#L145) there's still a comment about store-freeze being disabled, but then a few lines later that is added to metareducers.

**Comment by DorianGrey** [comment]
I knew I forgot something when merging the update...

Removed this and any another pending TODO comment in https://github.com/DorianGrey/ng-webpack-template/commit/deb18b441a885fe3a5fca75fdfd4dd966de56ba7 .
